import mysql.connector
from nsetools import nse

mydb = mysql.connector.connect(
    host="localhost",
    port="3306",
    user="root",
    password="",
    database="stock_quote"
)
m_cursor = mydb.cursor()

m_cursor.execute("""create table infy(date DATE,
                    adhocMargin VARCHAR(20), 
                    applicableMargin VARCHAR(20), 
                    averagePrice VARCHAR(20), 
                    bcEndDate VARCHAR(20), 
                    bcStartDate VARCHAR(20), 
                    buyPrice1 VARCHAR(20), 
                    buyPrice2 VARCHAR(20), 
                    buyPrice3 VARCHAR(20), 
                    buyPrice4 VARCHAR(20),
                    buyPrice5 VARCHAR(20),
                    buyQuantity1 VARCHAR(20),
                    buyQuantity2 VARCHAR(20), 
                    buyQuantity3 VARCHAR(20), 
                    buyQuantity4 VARCHAR(20), 
                    buyQuantity5 VARCHAR(20), 
                    change1 VARCHAR(20), 
                    closePrice VARCHAR(20), 
                    cm_adj_high_dt VARCHAR(20), 
                    cm_adj_low_dt VARCHAR(20), 
                    cm_ffm VARCHAR(20), 
                    companyName VARCHAR(20), 
                    css_status_desc VARCHAR(20), 
                    dayHigh VARCHAR(20), 
                    dayLow VARCHAR(20), 
                    deliveryQuantity VARCHAR(20), 
                    deliveryToTradedQuantity VARCHAR(20), 
                    exDate VARCHAR(20), 
                    extremeLossMargin VARCHAR(20), 
                    faceValue VARCHAR(20), 
                    high52 VARCHAR(20), 
                    indexVar VARCHAR(20), 
                    isinCode VARCHAR(20), 
                    lastPrice VARCHAR(20), 
                    low52 VARCHAR(20),
                    marketType VARCHAR(20), 
                    ndEndDate VARCHAR(20), 
                    ndStartDate VARCHAR(20), 
                    open1 VARCHAR(20), 
                    pChange VARCHAR(20), 
                    previousClose VARCHAR(20), 
                    priceBand VARCHAR(20), 
                    pricebandlower VARCHAR(20), 
                    pricebandupper VARCHAR(20), 
                    purpose VARCHAR(20), 
                    quantityTraded VARCHAR(20), 
                    recordDate VARCHAR(20), 
                    secDate VARCHAR(20), 
                    securityVar VARCHAR(20), 
                    sellPrice1 VARCHAR(20), 
                    sellPrice2 VARCHAR(20), 
                    sellPrice3 VARCHAR(20), 
                    sellPrice4 VARCHAR(20), 
                    sellPrice5 VARCHAR(20), 
                    sellQuantity1 VARCHAR(20), 
                    sellQuantity2 VARCHAR(20), 
                    sellQuantity3 VARCHAR(20), 
                    sellQuantity4 VARCHAR(20), 
                    sellQuantity5 VARCHAR(20), 
                    series VARCHAR(20),
                    symbol VARCHAR(20), 
                    totalBuyQuantity VARCHAR(20), 
                    totalSellQuantity VARCHAR(20), 
                    totalTradedValue VARCHAR(20), 
                    totalTradedVolume VARCHAR(20), 
                    varMargin VARCHAR(20))""")
m_cursor.close()
mydb.commit()
mydb.close()
